ALTER TABLE resolution_logs
  ADD COLUMN IF NOT EXISTS cache_hit BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS latency_ms INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prompt_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cached_prompt_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS output_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS thinking_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tool_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS search_queries INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_list_cost_usd NUMERIC(14, 8) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_resolution_logs_estimated_cost
  ON resolution_logs (estimated_list_cost_usd DESC);
